<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageDbData.aspx.cs" Inherits="WebFormsAccess.ManageDbData" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <style>
        .errorText {
            color: red;
            font-weight: bold;

        }
    </style>
    <form id="frmDbData" runat="server">
        <asp:SqlDataSource
            ID="dataSourceUsers"
            runat="server"
            ConnectionString='<%$ ConnectionStrings:CompanyDB %>' 
            SelectCommand="SELECT * FROM [Users]"
            InsertCommand="INSERT INTO Users(FirstName, LastName, Password) VALUES (@FirstName, @LastName, @Password)"
            UpdateCommand="UPDATE [Users] SET [FirstName] = @FirstName, [LastName] = @LastName, [Password] = @Password WHERE [UserID] = @UserID"
            DeleteCommand="DELETE FROM [Users] WHERE [UserID] = @UserID"
            >
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String"></asp:Parameter>
                <asp:Parameter Name="LastName" Type="String"></asp:Parameter>
                <asp:Parameter Name="Password" Type="String"></asp:Parameter>
                <asp:Parameter Name="UserID" Type="Int32"></asp:Parameter>
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="UserID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
            </InsertParameters>

        </asp:SqlDataSource>
        <div>
            <asp:GridView ID="gvUSers" runat="server" AutoGenerateColumns="False" DataSourceID="dataSourceUsers" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" PageSize="3">
                <Columns>
                    <asp:BoundField DataField="UserID" HeaderText="UserID" ReadOnly="True" InsertVisible="False" SortExpression="UserID"></asp:BoundField>
                    <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName"></asp:BoundField>
                    <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName"></asp:BoundField>
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password"></asp:BoundField>
                </Columns>
            </asp:GridView>
        
        
        </div>
        <div>
            Add User:
        </div>
        <table>
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Password</th>
                </tr>
                 </thead> 
                <tr>
                    <td><asp:TextBox ID="txtFirstName" runat="server"></asp:TextBox></td>
                    <td><asp:TextBox ID="txtLastName" runat="server"></asp:TextBox></td>
                    <td><asp:TextBox ID="txtPassword" runat="server" TextMode="Password"></asp:TextBox></td>
                </tr> 
            <tr>
                <td></td>
                <td></td>
                <td>
                    <asp:Button ID="btnAddUser" runat="server" OnClick="btnAddUser_Click" Text="Add"/>
                </td>
            </tr>
        </table>
        <asp:Label ID="lblErrorText" runat="server" CssClass="errorText"></asp:Label>
    </form>
</body>
</html>
